// <auto-generated />
namespace Emaill.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatedefault : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedefault));
        
        string IMigrationMetadata.Id
        {
            get { return "201701190807579_updatedefault"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
